# version: '3.8'

# services:
#   mysql:
#     image: mysql:latest
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: user
#       MYSQL_PASSWORD: passwd
#       MYSQL_DATABASE: db_aula
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql

#   nodejs-app:
#     build: .
#     container_name: nodejs-cloud-app
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mysql
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306
#       DB_USER: user
#       DB_PASSWORD: passwd
#       DB_NAME: db_aula

# volumes:
#   mysql-data:
